[workspace]
resolver = "2"
members = [
    "crates/quant_core",
    "crates/quant_exec",
]

[workspace.dependencies]
quant_core = {path = "crates/quant_core"}
quant_exec = {path = "crates/quant_exec"}

ndarray = "0.17.2"
ndarray-linalg = "0.18.1"
rust_decimal = {version = "1.43.0", features = ["serde"]}

clap = {version = "4.6.6", features = ["derive"]}
serde = {version = "1.0.229", features = ["derive"]}
serde_json = "1.0.151"
csv = "1.4.0"

thiserror = "2.0.20"
anyhow = "1.0.104"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"